In [1]:
from mxnet import nd

In [2]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [3]:
x.shape

(12,)

In [4]:
x.size

12

In [5]:
s = x.reshape((3,4))
s


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [6]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [7]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [8]:
y = nd.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [9]:
nd.random.normal(0,1,shape=(3,4))


[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>

In [10]:
s + y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [11]:
s * y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [12]:
s / y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [13]:
y.exp() #y按元素做指数运算


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [14]:
nd.dot(s,y.T) #矩阵乘法  s与y的转置


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [15]:
nd.concat(s, y, dim=0), nd.concat(s , y, dim=1) #分别是在行上（dim=0）和在列上（dim=1）进行连接两个矩阵

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  1.  4.  3.]
  [ 1.  2.  3.  4.]
  [ 4.  3.  2.  1.]]
 <NDArray 6x4 @cpu(0)>,
 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
  [ 4.  5.  6.  7.  1.  2.  3.  4.]
  [ 8.  9. 10. 11.  4.  3.  2.  1.]]
 <NDArray 3x8 @cpu(0)>)

In [16]:
s == y #根据各个元素位置上的数值相同为1，反之为0，从而生成一个判断矩阵


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [17]:
s.sum()


[66.]
<NDArray 1 @cpu(0)>

In [18]:
s.norm().asscalar() #通过asscalar函数将结果转换为Python中的标量

22.494442

In [19]:
a = nd.arange(3).reshape((3,1))
b = nd.arange(2).reshape((1,2))
a ,b 

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [20]:
a + b #当计算的两个形状不同的NDarray按元素计算时，可能触发广播（broadcasting），通过适当的转换成相对应的形状


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [21]:
s[1:3] #行索引


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [22]:
s[1, 2] = 9 #具体修改到具体的位置
s


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [23]:
s[1:2 , :] = 12 #仅仅只是修改其中的一行
s


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [24]:
before = id(y)
y = y + s
id(y) == before  #如果两个实例的ID一致的话，那么他们的对应的内存地址应该是一致的，反之则不同

False

In [25]:
z = y.zeros_like()
before = id(z)
z[:] = s + y 
id(z) == before

True

In [26]:
import numpy as np

In [27]:
p = np.ones((2,3))
d = nd.array(p)
d


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [28]:
d.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [29]:
#自动求梯度
from mxnet import autograd, nd

In [30]:
x = nd.arange(4).reshape((4,1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [33]:
x.attach_grad() #申请存储梯度的内存

In [34]:
with autograd.record():    #通过record函数来要求网络记录有关的梯度计算，默认情况下是没有的
    y = 2 * nd.dot(x.T,x)

In [35]:
y.backward() #通过backward函数自动求解梯度

In [36]:
assert(x.grad - 4 * x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [37]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True


In [42]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0 :
        c = b
    else:
        c = 100 * b
    return c

In [43]:
a = nd.random.normal(shape = 1)
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()

In [44]:
a.grad == c / a


[1.]
<NDArray 1 @cpu(0)>

In [ ]:
# MXnet提供了autograd模块自动化求导过程
# autograd模块对于一般的命令式程序进行求导
# MXnet的运行模式包括训练模式和预测模式，通过autograd.is_training()